//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace openid.CRMwebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BFCRMWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BFCRMWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCardDataJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardPointJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardPointExpireJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdCardPointUseJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardPointUseListJOSNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardBuyListJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustDataJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdCustDataJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsApplyCardJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdGetMsgEpaperJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEcouponListJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsEcouponDataJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMemberJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegistVerifyJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountIsLockJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdAccountLockFieldJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLoginVerifyJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetForgetVerifyJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOldRegistVerifyJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrmUpdAccountLockFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrmUpdateEmailFieldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BFCRMWebService() {
            this.Url = global::openid.Properties.Settings.Default.openid_CRMwebReference_BFCRMWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCardDataJSONCompletedEventHandler GetCardDataJSONCompleted;
        
        /// <remarks/>
        public event GetCardPointJSONCompletedEventHandler GetCardPointJSONCompleted;
        
        /// <remarks/>
        public event GetCardPointExpireJSONCompletedEventHandler GetCardPointExpireJSONCompleted;
        
        /// <remarks/>
        public event UpdCardPointUseJSONCompletedEventHandler UpdCardPointUseJSONCompleted;
        
        /// <remarks/>
        public event GetCardPointUseListJOSNCompletedEventHandler GetCardPointUseListJOSNCompleted;
        
        /// <remarks/>
        public event GetCardBuyListJSONCompletedEventHandler GetCardBuyListJSONCompleted;
        
        /// <remarks/>
        public event GetCustDataJSONCompletedEventHandler GetCustDataJSONCompleted;
        
        /// <remarks/>
        public event UpdCustDataJSONCompletedEventHandler UpdCustDataJSONCompleted;
        
        /// <remarks/>
        public event InsApplyCardJSONCompletedEventHandler InsApplyCardJSONCompleted;
        
        /// <remarks/>
        public event UpdGetMsgEpaperJSONCompletedEventHandler UpdGetMsgEpaperJSONCompleted;
        
        /// <remarks/>
        public event GetEcouponListJSONCompletedEventHandler GetEcouponListJSONCompleted;
        
        /// <remarks/>
        public event InsEcouponDataJSONCompletedEventHandler InsEcouponDataJSONCompleted;
        
        /// <remarks/>
        public event CreateMemberJSONCompletedEventHandler CreateMemberJSONCompleted;
        
        /// <remarks/>
        public event GetRegistVerifyJSONCompletedEventHandler GetRegistVerifyJSONCompleted;
        
        /// <remarks/>
        public event GetAccountIsLockJSONCompletedEventHandler GetAccountIsLockJSONCompleted;
        
        /// <remarks/>
        public event UpdAccountLockFieldJSONCompletedEventHandler UpdAccountLockFieldJSONCompleted;
        
        /// <remarks/>
        public event GetLoginVerifyJSONCompletedEventHandler GetLoginVerifyJSONCompleted;
        
        /// <remarks/>
        public event GetForgetVerifyJSONCompletedEventHandler GetForgetVerifyJSONCompleted;
        
        /// <remarks/>
        public event GetOldRegistVerifyJSONCompletedEventHandler GetOldRegistVerifyJSONCompleted;
        
        /// <remarks/>
        public event CrmUpdAccountLockFieldCompletedEventHandler CrmUpdAccountLockFieldCompleted;
        
        /// <remarks/>
        public event CrmUpdateEmailFieldCompletedEventHandler CrmUpdateEmailFieldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardDataJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardDataJSON(string strPapersID) {
            object[] results = this.Invoke("GetCardDataJSON", new object[] {
                        strPapersID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardDataJSONAsync(string strPapersID) {
            this.GetCardDataJSONAsync(strPapersID, null);
        }
        
        /// <remarks/>
        public void GetCardDataJSONAsync(string strPapersID, object userState) {
            if ((this.GetCardDataJSONOperationCompleted == null)) {
                this.GetCardDataJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardDataJSONOperationCompleted);
            }
            this.InvokeAsync("GetCardDataJSON", new object[] {
                        strPapersID}, this.GetCardDataJSONOperationCompleted, userState);
        }
        
        private void OnGetCardDataJSONOperationCompleted(object arg) {
            if ((this.GetCardDataJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardDataJSONCompleted(this, new GetCardDataJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardPointJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardPointJSON(string strCustNo) {
            object[] results = this.Invoke("GetCardPointJSON", new object[] {
                        strCustNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardPointJSONAsync(string strCustNo) {
            this.GetCardPointJSONAsync(strCustNo, null);
        }
        
        /// <remarks/>
        public void GetCardPointJSONAsync(string strCustNo, object userState) {
            if ((this.GetCardPointJSONOperationCompleted == null)) {
                this.GetCardPointJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardPointJSONOperationCompleted);
            }
            this.InvokeAsync("GetCardPointJSON", new object[] {
                        strCustNo}, this.GetCardPointJSONOperationCompleted, userState);
        }
        
        private void OnGetCardPointJSONOperationCompleted(object arg) {
            if ((this.GetCardPointJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardPointJSONCompleted(this, new GetCardPointJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardPointExpireJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardPointExpireJSON(string strCardNo) {
            object[] results = this.Invoke("GetCardPointExpireJSON", new object[] {
                        strCardNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardPointExpireJSONAsync(string strCardNo) {
            this.GetCardPointExpireJSONAsync(strCardNo, null);
        }
        
        /// <remarks/>
        public void GetCardPointExpireJSONAsync(string strCardNo, object userState) {
            if ((this.GetCardPointExpireJSONOperationCompleted == null)) {
                this.GetCardPointExpireJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardPointExpireJSONOperationCompleted);
            }
            this.InvokeAsync("GetCardPointExpireJSON", new object[] {
                        strCardNo}, this.GetCardPointExpireJSONOperationCompleted, userState);
        }
        
        private void OnGetCardPointExpireJSONOperationCompleted(object arg) {
            if ((this.GetCardPointExpireJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardPointExpireJSONCompleted(this, new GetCardPointExpireJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdCardPointUseJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdCardPointUseJSON(string strFlag, string strPoint, string strCustNo, string strUseItem, string strProfitCenter) {
            object[] results = this.Invoke("UpdCardPointUseJSON", new object[] {
                        strFlag,
                        strPoint,
                        strCustNo,
                        strUseItem,
                        strProfitCenter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdCardPointUseJSONAsync(string strFlag, string strPoint, string strCustNo, string strUseItem, string strProfitCenter) {
            this.UpdCardPointUseJSONAsync(strFlag, strPoint, strCustNo, strUseItem, strProfitCenter, null);
        }
        
        /// <remarks/>
        public void UpdCardPointUseJSONAsync(string strFlag, string strPoint, string strCustNo, string strUseItem, string strProfitCenter, object userState) {
            if ((this.UpdCardPointUseJSONOperationCompleted == null)) {
                this.UpdCardPointUseJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdCardPointUseJSONOperationCompleted);
            }
            this.InvokeAsync("UpdCardPointUseJSON", new object[] {
                        strFlag,
                        strPoint,
                        strCustNo,
                        strUseItem,
                        strProfitCenter}, this.UpdCardPointUseJSONOperationCompleted, userState);
        }
        
        private void OnUpdCardPointUseJSONOperationCompleted(object arg) {
            if ((this.UpdCardPointUseJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdCardPointUseJSONCompleted(this, new UpdCardPointUseJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardPointUseListJOSN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardPointUseListJOSN(string strCustNo, string strStartDate, string strEndDate) {
            object[] results = this.Invoke("GetCardPointUseListJOSN", new object[] {
                        strCustNo,
                        strStartDate,
                        strEndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardPointUseListJOSNAsync(string strCustNo, string strStartDate, string strEndDate) {
            this.GetCardPointUseListJOSNAsync(strCustNo, strStartDate, strEndDate, null);
        }
        
        /// <remarks/>
        public void GetCardPointUseListJOSNAsync(string strCustNo, string strStartDate, string strEndDate, object userState) {
            if ((this.GetCardPointUseListJOSNOperationCompleted == null)) {
                this.GetCardPointUseListJOSNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardPointUseListJOSNOperationCompleted);
            }
            this.InvokeAsync("GetCardPointUseListJOSN", new object[] {
                        strCustNo,
                        strStartDate,
                        strEndDate}, this.GetCardPointUseListJOSNOperationCompleted, userState);
        }
        
        private void OnGetCardPointUseListJOSNOperationCompleted(object arg) {
            if ((this.GetCardPointUseListJOSNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardPointUseListJOSNCompleted(this, new GetCardPointUseListJOSNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCardBuyListJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardBuyListJSON(string strCustNo, string strStartDate, string strEndDate) {
            object[] results = this.Invoke("GetCardBuyListJSON", new object[] {
                        strCustNo,
                        strStartDate,
                        strEndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardBuyListJSONAsync(string strCustNo, string strStartDate, string strEndDate) {
            this.GetCardBuyListJSONAsync(strCustNo, strStartDate, strEndDate, null);
        }
        
        /// <remarks/>
        public void GetCardBuyListJSONAsync(string strCustNo, string strStartDate, string strEndDate, object userState) {
            if ((this.GetCardBuyListJSONOperationCompleted == null)) {
                this.GetCardBuyListJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardBuyListJSONOperationCompleted);
            }
            this.InvokeAsync("GetCardBuyListJSON", new object[] {
                        strCustNo,
                        strStartDate,
                        strEndDate}, this.GetCardBuyListJSONOperationCompleted, userState);
        }
        
        private void OnGetCardBuyListJSONOperationCompleted(object arg) {
            if ((this.GetCardBuyListJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardBuyListJSONCompleted(this, new GetCardBuyListJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustDataJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCustDataJSON(string strCustNo, string strCardNo, string strName, string strPapersID, string strMobilePhone, string strEmail) {
            object[] results = this.Invoke("GetCustDataJSON", new object[] {
                        strCustNo,
                        strCardNo,
                        strName,
                        strPapersID,
                        strMobilePhone,
                        strEmail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustDataJSONAsync(string strCustNo, string strCardNo, string strName, string strPapersID, string strMobilePhone, string strEmail) {
            this.GetCustDataJSONAsync(strCustNo, strCardNo, strName, strPapersID, strMobilePhone, strEmail, null);
        }
        
        /// <remarks/>
        public void GetCustDataJSONAsync(string strCustNo, string strCardNo, string strName, string strPapersID, string strMobilePhone, string strEmail, object userState) {
            if ((this.GetCustDataJSONOperationCompleted == null)) {
                this.GetCustDataJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustDataJSONOperationCompleted);
            }
            this.InvokeAsync("GetCustDataJSON", new object[] {
                        strCustNo,
                        strCardNo,
                        strName,
                        strPapersID,
                        strMobilePhone,
                        strEmail}, this.GetCustDataJSONOperationCompleted, userState);
        }
        
        private void OnGetCustDataJSONOperationCompleted(object arg) {
            if ((this.GetCustDataJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustDataJSONCompleted(this, new GetCustDataJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdCustDataJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdCustDataJSON(string strCustNo, string strMobilePhone, string strAddress_ZipCode, string strAddress, string strEmail, string strHobby, string strInterest, string IsVerify) {
            object[] results = this.Invoke("UpdCustDataJSON", new object[] {
                        strCustNo,
                        strMobilePhone,
                        strAddress_ZipCode,
                        strAddress,
                        strEmail,
                        strHobby,
                        strInterest,
                        IsVerify});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdCustDataJSONAsync(string strCustNo, string strMobilePhone, string strAddress_ZipCode, string strAddress, string strEmail, string strHobby, string strInterest, string IsVerify) {
            this.UpdCustDataJSONAsync(strCustNo, strMobilePhone, strAddress_ZipCode, strAddress, strEmail, strHobby, strInterest, IsVerify, null);
        }
        
        /// <remarks/>
        public void UpdCustDataJSONAsync(string strCustNo, string strMobilePhone, string strAddress_ZipCode, string strAddress, string strEmail, string strHobby, string strInterest, string IsVerify, object userState) {
            if ((this.UpdCustDataJSONOperationCompleted == null)) {
                this.UpdCustDataJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdCustDataJSONOperationCompleted);
            }
            this.InvokeAsync("UpdCustDataJSON", new object[] {
                        strCustNo,
                        strMobilePhone,
                        strAddress_ZipCode,
                        strAddress,
                        strEmail,
                        strHobby,
                        strInterest,
                        IsVerify}, this.UpdCustDataJSONOperationCompleted, userState);
        }
        
        private void OnUpdCustDataJSONOperationCompleted(object arg) {
            if ((this.UpdCustDataJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdCustDataJSONCompleted(this, new UpdCustDataJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsApplyCardJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsApplyCardJSON(
                    string strGUID, 
                    string strName, 
                    string PapersType, 
                    string PapersID, 
                    string strSex, 
                    string strBirthday, 
                    string TelPhone_Tel, 
                    string strMobilePhone, 
                    string strAddress_ZipCode, 
                    string strAddress, 
                    string strEmail, 
                    string strHobby, 
                    string strInterest, 
                    string CardType, 
                    string CardKind, 
                    string Apply_Store) {
            object[] results = this.Invoke("InsApplyCardJSON", new object[] {
                        strGUID,
                        strName,
                        PapersType,
                        PapersID,
                        strSex,
                        strBirthday,
                        TelPhone_Tel,
                        strMobilePhone,
                        strAddress_ZipCode,
                        strAddress,
                        strEmail,
                        strHobby,
                        strInterest,
                        CardType,
                        CardKind,
                        Apply_Store});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsApplyCardJSONAsync(
                    string strGUID, 
                    string strName, 
                    string PapersType, 
                    string PapersID, 
                    string strSex, 
                    string strBirthday, 
                    string TelPhone_Tel, 
                    string strMobilePhone, 
                    string strAddress_ZipCode, 
                    string strAddress, 
                    string strEmail, 
                    string strHobby, 
                    string strInterest, 
                    string CardType, 
                    string CardKind, 
                    string Apply_Store) {
            this.InsApplyCardJSONAsync(strGUID, strName, PapersType, PapersID, strSex, strBirthday, TelPhone_Tel, strMobilePhone, strAddress_ZipCode, strAddress, strEmail, strHobby, strInterest, CardType, CardKind, Apply_Store, null);
        }
        
        /// <remarks/>
        public void InsApplyCardJSONAsync(
                    string strGUID, 
                    string strName, 
                    string PapersType, 
                    string PapersID, 
                    string strSex, 
                    string strBirthday, 
                    string TelPhone_Tel, 
                    string strMobilePhone, 
                    string strAddress_ZipCode, 
                    string strAddress, 
                    string strEmail, 
                    string strHobby, 
                    string strInterest, 
                    string CardType, 
                    string CardKind, 
                    string Apply_Store, 
                    object userState) {
            if ((this.InsApplyCardJSONOperationCompleted == null)) {
                this.InsApplyCardJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsApplyCardJSONOperationCompleted);
            }
            this.InvokeAsync("InsApplyCardJSON", new object[] {
                        strGUID,
                        strName,
                        PapersType,
                        PapersID,
                        strSex,
                        strBirthday,
                        TelPhone_Tel,
                        strMobilePhone,
                        strAddress_ZipCode,
                        strAddress,
                        strEmail,
                        strHobby,
                        strInterest,
                        CardType,
                        CardKind,
                        Apply_Store}, this.InsApplyCardJSONOperationCompleted, userState);
        }
        
        private void OnInsApplyCardJSONOperationCompleted(object arg) {
            if ((this.InsApplyCardJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsApplyCardJSONCompleted(this, new InsApplyCardJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdGetMsgEpaperJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdGetMsgEpaperJSON(string strCustNo, string strIsMsg, string strIsEpaper) {
            object[] results = this.Invoke("UpdGetMsgEpaperJSON", new object[] {
                        strCustNo,
                        strIsMsg,
                        strIsEpaper});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdGetMsgEpaperJSONAsync(string strCustNo, string strIsMsg, string strIsEpaper) {
            this.UpdGetMsgEpaperJSONAsync(strCustNo, strIsMsg, strIsEpaper, null);
        }
        
        /// <remarks/>
        public void UpdGetMsgEpaperJSONAsync(string strCustNo, string strIsMsg, string strIsEpaper, object userState) {
            if ((this.UpdGetMsgEpaperJSONOperationCompleted == null)) {
                this.UpdGetMsgEpaperJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdGetMsgEpaperJSONOperationCompleted);
            }
            this.InvokeAsync("UpdGetMsgEpaperJSON", new object[] {
                        strCustNo,
                        strIsMsg,
                        strIsEpaper}, this.UpdGetMsgEpaperJSONOperationCompleted, userState);
        }
        
        private void OnUpdGetMsgEpaperJSONOperationCompleted(object arg) {
            if ((this.UpdGetMsgEpaperJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdGetMsgEpaperJSONCompleted(this, new UpdGetMsgEpaperJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEcouponListJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEcouponListJSON(string strCustNo) {
            object[] results = this.Invoke("GetEcouponListJSON", new object[] {
                        strCustNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEcouponListJSONAsync(string strCustNo) {
            this.GetEcouponListJSONAsync(strCustNo, null);
        }
        
        /// <remarks/>
        public void GetEcouponListJSONAsync(string strCustNo, object userState) {
            if ((this.GetEcouponListJSONOperationCompleted == null)) {
                this.GetEcouponListJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEcouponListJSONOperationCompleted);
            }
            this.InvokeAsync("GetEcouponListJSON", new object[] {
                        strCustNo}, this.GetEcouponListJSONOperationCompleted, userState);
        }
        
        private void OnGetEcouponListJSONOperationCompleted(object arg) {
            if ((this.GetEcouponListJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEcouponListJSONCompleted(this, new GetEcouponListJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsEcouponDataJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsEcouponDataJSON(string strCardNo, string EcouponID, string strActionID, string DiscountMoney, string CanUseEndDate) {
            object[] results = this.Invoke("InsEcouponDataJSON", new object[] {
                        strCardNo,
                        EcouponID,
                        strActionID,
                        DiscountMoney,
                        CanUseEndDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsEcouponDataJSONAsync(string strCardNo, string EcouponID, string strActionID, string DiscountMoney, string CanUseEndDate) {
            this.InsEcouponDataJSONAsync(strCardNo, EcouponID, strActionID, DiscountMoney, CanUseEndDate, null);
        }
        
        /// <remarks/>
        public void InsEcouponDataJSONAsync(string strCardNo, string EcouponID, string strActionID, string DiscountMoney, string CanUseEndDate, object userState) {
            if ((this.InsEcouponDataJSONOperationCompleted == null)) {
                this.InsEcouponDataJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsEcouponDataJSONOperationCompleted);
            }
            this.InvokeAsync("InsEcouponDataJSON", new object[] {
                        strCardNo,
                        EcouponID,
                        strActionID,
                        DiscountMoney,
                        CanUseEndDate}, this.InsEcouponDataJSONOperationCompleted, userState);
        }
        
        private void OnInsEcouponDataJSONOperationCompleted(object arg) {
            if ((this.InsEcouponDataJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsEcouponDataJSONCompleted(this, new InsEcouponDataJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateMemberJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateMemberJSON(string strCardKind, string strName, string strPapersType, string strPapersID, string strBirthday, string strSex, string strMobilePhone, string strEmail, string strAdd) {
            object[] results = this.Invoke("CreateMemberJSON", new object[] {
                        strCardKind,
                        strName,
                        strPapersType,
                        strPapersID,
                        strBirthday,
                        strSex,
                        strMobilePhone,
                        strEmail,
                        strAdd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateMemberJSONAsync(string strCardKind, string strName, string strPapersType, string strPapersID, string strBirthday, string strSex, string strMobilePhone, string strEmail, string strAdd) {
            this.CreateMemberJSONAsync(strCardKind, strName, strPapersType, strPapersID, strBirthday, strSex, strMobilePhone, strEmail, strAdd, null);
        }
        
        /// <remarks/>
        public void CreateMemberJSONAsync(string strCardKind, string strName, string strPapersType, string strPapersID, string strBirthday, string strSex, string strMobilePhone, string strEmail, string strAdd, object userState) {
            if ((this.CreateMemberJSONOperationCompleted == null)) {
                this.CreateMemberJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMemberJSONOperationCompleted);
            }
            this.InvokeAsync("CreateMemberJSON", new object[] {
                        strCardKind,
                        strName,
                        strPapersType,
                        strPapersID,
                        strBirthday,
                        strSex,
                        strMobilePhone,
                        strEmail,
                        strAdd}, this.CreateMemberJSONOperationCompleted, userState);
        }
        
        private void OnCreateMemberJSONOperationCompleted(object arg) {
            if ((this.CreateMemberJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMemberJSONCompleted(this, new CreateMemberJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRegistVerifyJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRegistVerifyJSON(string strCardNo, string strPapersID) {
            object[] results = this.Invoke("GetRegistVerifyJSON", new object[] {
                        strCardNo,
                        strPapersID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRegistVerifyJSONAsync(string strCardNo, string strPapersID) {
            this.GetRegistVerifyJSONAsync(strCardNo, strPapersID, null);
        }
        
        /// <remarks/>
        public void GetRegistVerifyJSONAsync(string strCardNo, string strPapersID, object userState) {
            if ((this.GetRegistVerifyJSONOperationCompleted == null)) {
                this.GetRegistVerifyJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegistVerifyJSONOperationCompleted);
            }
            this.InvokeAsync("GetRegistVerifyJSON", new object[] {
                        strCardNo,
                        strPapersID}, this.GetRegistVerifyJSONOperationCompleted, userState);
        }
        
        private void OnGetRegistVerifyJSONOperationCompleted(object arg) {
            if ((this.GetRegistVerifyJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegistVerifyJSONCompleted(this, new GetRegistVerifyJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccountIsLockJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountIsLockJSON(string strCustNo, string strFlag, string strValue) {
            object[] results = this.Invoke("GetAccountIsLockJSON", new object[] {
                        strCustNo,
                        strFlag,
                        strValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountIsLockJSONAsync(string strCustNo, string strFlag, string strValue) {
            this.GetAccountIsLockJSONAsync(strCustNo, strFlag, strValue, null);
        }
        
        /// <remarks/>
        public void GetAccountIsLockJSONAsync(string strCustNo, string strFlag, string strValue, object userState) {
            if ((this.GetAccountIsLockJSONOperationCompleted == null)) {
                this.GetAccountIsLockJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountIsLockJSONOperationCompleted);
            }
            this.InvokeAsync("GetAccountIsLockJSON", new object[] {
                        strCustNo,
                        strFlag,
                        strValue}, this.GetAccountIsLockJSONOperationCompleted, userState);
        }
        
        private void OnGetAccountIsLockJSONOperationCompleted(object arg) {
            if ((this.GetAccountIsLockJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountIsLockJSONCompleted(this, new GetAccountIsLockJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdAccountLockFieldJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdAccountLockFieldJSON(string strCustNo, string strFlag, string strValue) {
            object[] results = this.Invoke("UpdAccountLockFieldJSON", new object[] {
                        strCustNo,
                        strFlag,
                        strValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdAccountLockFieldJSONAsync(string strCustNo, string strFlag, string strValue) {
            this.UpdAccountLockFieldJSONAsync(strCustNo, strFlag, strValue, null);
        }
        
        /// <remarks/>
        public void UpdAccountLockFieldJSONAsync(string strCustNo, string strFlag, string strValue, object userState) {
            if ((this.UpdAccountLockFieldJSONOperationCompleted == null)) {
                this.UpdAccountLockFieldJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdAccountLockFieldJSONOperationCompleted);
            }
            this.InvokeAsync("UpdAccountLockFieldJSON", new object[] {
                        strCustNo,
                        strFlag,
                        strValue}, this.UpdAccountLockFieldJSONOperationCompleted, userState);
        }
        
        private void OnUpdAccountLockFieldJSONOperationCompleted(object arg) {
            if ((this.UpdAccountLockFieldJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdAccountLockFieldJSONCompleted(this, new UpdAccountLockFieldJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLoginVerifyJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLoginVerifyJSON(string strAccount) {
            object[] results = this.Invoke("GetLoginVerifyJSON", new object[] {
                        strAccount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLoginVerifyJSONAsync(string strAccount) {
            this.GetLoginVerifyJSONAsync(strAccount, null);
        }
        
        /// <remarks/>
        public void GetLoginVerifyJSONAsync(string strAccount, object userState) {
            if ((this.GetLoginVerifyJSONOperationCompleted == null)) {
                this.GetLoginVerifyJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLoginVerifyJSONOperationCompleted);
            }
            this.InvokeAsync("GetLoginVerifyJSON", new object[] {
                        strAccount}, this.GetLoginVerifyJSONOperationCompleted, userState);
        }
        
        private void OnGetLoginVerifyJSONOperationCompleted(object arg) {
            if ((this.GetLoginVerifyJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLoginVerifyJSONCompleted(this, new GetLoginVerifyJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetForgetVerifyJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetForgetVerifyJSON(string strPapersID, string strBirthday, string strFlag, string strValue) {
            object[] results = this.Invoke("GetForgetVerifyJSON", new object[] {
                        strPapersID,
                        strBirthday,
                        strFlag,
                        strValue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetForgetVerifyJSONAsync(string strPapersID, string strBirthday, string strFlag, string strValue) {
            this.GetForgetVerifyJSONAsync(strPapersID, strBirthday, strFlag, strValue, null);
        }
        
        /// <remarks/>
        public void GetForgetVerifyJSONAsync(string strPapersID, string strBirthday, string strFlag, string strValue, object userState) {
            if ((this.GetForgetVerifyJSONOperationCompleted == null)) {
                this.GetForgetVerifyJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetForgetVerifyJSONOperationCompleted);
            }
            this.InvokeAsync("GetForgetVerifyJSON", new object[] {
                        strPapersID,
                        strBirthday,
                        strFlag,
                        strValue}, this.GetForgetVerifyJSONOperationCompleted, userState);
        }
        
        private void OnGetForgetVerifyJSONOperationCompleted(object arg) {
            if ((this.GetForgetVerifyJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetForgetVerifyJSONCompleted(this, new GetForgetVerifyJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOldRegistVerifyJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOldRegistVerifyJSON(string strAllPapersID) {
            object[] results = this.Invoke("GetOldRegistVerifyJSON", new object[] {
                        strAllPapersID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOldRegistVerifyJSONAsync(string strAllPapersID) {
            this.GetOldRegistVerifyJSONAsync(strAllPapersID, null);
        }
        
        /// <remarks/>
        public void GetOldRegistVerifyJSONAsync(string strAllPapersID, object userState) {
            if ((this.GetOldRegistVerifyJSONOperationCompleted == null)) {
                this.GetOldRegistVerifyJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOldRegistVerifyJSONOperationCompleted);
            }
            this.InvokeAsync("GetOldRegistVerifyJSON", new object[] {
                        strAllPapersID}, this.GetOldRegistVerifyJSONOperationCompleted, userState);
        }
        
        private void OnGetOldRegistVerifyJSONOperationCompleted(object arg) {
            if ((this.GetOldRegistVerifyJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOldRegistVerifyJSONCompleted(this, new GetOldRegistVerifyJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrmUpdAccountLockField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("code")]
        public string CrmUpdAccountLockField(int vipId, string strEmail, string strFlag, string strValue, out string msg) {
            object[] results = this.Invoke("CrmUpdAccountLockField", new object[] {
                        vipId,
                        strEmail,
                        strFlag,
                        strValue});
            msg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrmUpdAccountLockFieldAsync(int vipId, string strEmail, string strFlag, string strValue) {
            this.CrmUpdAccountLockFieldAsync(vipId, strEmail, strFlag, strValue, null);
        }
        
        /// <remarks/>
        public void CrmUpdAccountLockFieldAsync(int vipId, string strEmail, string strFlag, string strValue, object userState) {
            if ((this.CrmUpdAccountLockFieldOperationCompleted == null)) {
                this.CrmUpdAccountLockFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrmUpdAccountLockFieldOperationCompleted);
            }
            this.InvokeAsync("CrmUpdAccountLockField", new object[] {
                        vipId,
                        strEmail,
                        strFlag,
                        strValue}, this.CrmUpdAccountLockFieldOperationCompleted, userState);
        }
        
        private void OnCrmUpdAccountLockFieldOperationCompleted(object arg) {
            if ((this.CrmUpdAccountLockFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrmUpdAccountLockFieldCompleted(this, new CrmUpdAccountLockFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrmUpdateEmailField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("code")]
        public string CrmUpdateEmailField(int vipId, string strInitEmail, string strNewEmail, out string msg) {
            object[] results = this.Invoke("CrmUpdateEmailField", new object[] {
                        vipId,
                        strInitEmail,
                        strNewEmail});
            msg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrmUpdateEmailFieldAsync(int vipId, string strInitEmail, string strNewEmail) {
            this.CrmUpdateEmailFieldAsync(vipId, strInitEmail, strNewEmail, null);
        }
        
        /// <remarks/>
        public void CrmUpdateEmailFieldAsync(int vipId, string strInitEmail, string strNewEmail, object userState) {
            if ((this.CrmUpdateEmailFieldOperationCompleted == null)) {
                this.CrmUpdateEmailFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrmUpdateEmailFieldOperationCompleted);
            }
            this.InvokeAsync("CrmUpdateEmailField", new object[] {
                        vipId,
                        strInitEmail,
                        strNewEmail}, this.CrmUpdateEmailFieldOperationCompleted, userState);
        }
        
        private void OnCrmUpdateEmailFieldOperationCompleted(object arg) {
            if ((this.CrmUpdateEmailFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrmUpdateEmailFieldCompleted(this, new CrmUpdateEmailFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCardDataJSONCompletedEventHandler(object sender, GetCardDataJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardDataJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardDataJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCardPointJSONCompletedEventHandler(object sender, GetCardPointJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardPointJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardPointJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCardPointExpireJSONCompletedEventHandler(object sender, GetCardPointExpireJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardPointExpireJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardPointExpireJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UpdCardPointUseJSONCompletedEventHandler(object sender, UpdCardPointUseJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdCardPointUseJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdCardPointUseJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCardPointUseListJOSNCompletedEventHandler(object sender, GetCardPointUseListJOSNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardPointUseListJOSNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardPointUseListJOSNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCardBuyListJSONCompletedEventHandler(object sender, GetCardBuyListJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardBuyListJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardBuyListJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetCustDataJSONCompletedEventHandler(object sender, GetCustDataJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustDataJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustDataJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UpdCustDataJSONCompletedEventHandler(object sender, UpdCustDataJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdCustDataJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdCustDataJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void InsApplyCardJSONCompletedEventHandler(object sender, InsApplyCardJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsApplyCardJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsApplyCardJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UpdGetMsgEpaperJSONCompletedEventHandler(object sender, UpdGetMsgEpaperJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdGetMsgEpaperJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdGetMsgEpaperJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetEcouponListJSONCompletedEventHandler(object sender, GetEcouponListJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEcouponListJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEcouponListJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void InsEcouponDataJSONCompletedEventHandler(object sender, InsEcouponDataJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsEcouponDataJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsEcouponDataJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CreateMemberJSONCompletedEventHandler(object sender, CreateMemberJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMemberJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMemberJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetRegistVerifyJSONCompletedEventHandler(object sender, GetRegistVerifyJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegistVerifyJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegistVerifyJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetAccountIsLockJSONCompletedEventHandler(object sender, GetAccountIsLockJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountIsLockJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountIsLockJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void UpdAccountLockFieldJSONCompletedEventHandler(object sender, UpdAccountLockFieldJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdAccountLockFieldJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdAccountLockFieldJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetLoginVerifyJSONCompletedEventHandler(object sender, GetLoginVerifyJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLoginVerifyJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLoginVerifyJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetForgetVerifyJSONCompletedEventHandler(object sender, GetForgetVerifyJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetForgetVerifyJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetForgetVerifyJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetOldRegistVerifyJSONCompletedEventHandler(object sender, GetOldRegistVerifyJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOldRegistVerifyJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOldRegistVerifyJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CrmUpdAccountLockFieldCompletedEventHandler(object sender, CrmUpdAccountLockFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrmUpdAccountLockFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrmUpdAccountLockFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CrmUpdateEmailFieldCompletedEventHandler(object sender, CrmUpdateEmailFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrmUpdateEmailFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrmUpdateEmailFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591